### ISSUE TITLE
Add Delete Column to ReviewTable

### ISSUE THREAD

**Issue by crdgdr** [ucsb-cs156-f22/team03-f22-6pm-2#19]

**Comment by christianvanstralen** [comment]
# Acceptance Criteria
- [x] Delete column is added to MenuItemReviewTable
- [x] Existing MenuItemReview items can be deleted from the table
- [x] Items no longer appear on the table when/after deleted
- [ ] Passes `npm run coverage` and `npx stryker run` tests
- [ ] Passes all GitHub tests
