### ISSUE TITLE
Add ReviewTable component to Storybook

### ISSUE THREAD

**Issue by crdgdr** [ucsb-cs156-f22/team03-f22-6pm-2#22]

**Comment by christianvanstralen** [comment]
# Acceptance Criteria
- [x] A MenuItemReviewTable component appears in storybook properly
- [x] MenuItemReviews are displayed correctly for the zero, one, and three items in table
- [x] The headers and accessors in the table match up correctly to the variables defined from team02
- [x] Passes `npm run coverage` and `npx stryker run` tests
- [x] Passes GitHub tests
