### ISSUE TITLE
Add Placeholder for Review Index Page

### ISSUE THREAD

**Issue by crdgdr** [ucsb-cs156-f22/team03-f22-6pm-2#23]

**Comment by christianvanstralen** [comment]
# Acceptance Criteria
- [x] When `List Menu Item Reviews` is clicked, it shows the placeholder page at the route `/MenuItemReview/list`
- [x] When `Create Menu Item Reviews` is clicked, it shows the placeholder page at the route `/MenuItemReview/create`
- [x] Passes `npm run coverage` and `npx stryker run` tests
- [x] All GitHub tests/checks are passed
